# Generated automatically from Makefile.in by configure.
MAKEINFO  = makeinfo
TEXI_OBJS = openal.info

.SUFFIXES: .texi .info
%.info : %.texi ../config.h
	$(MAKEINFO) $<

all:	$(TEXI_OBJS)

clean:
	-rm -f $(TEXI_OBJS)

install:
	@echo "blah blah blah blah blah"

distclean: clean
	-rm -Rf Makefile
