/* fob/config.h.  Generated by configure.  */
/* fob/config.h.in.  Generated from configure.in by autoheader.  */

/* major */
#define FOB_MAJOR_VERSION 1

/* micro */
#define FOB_MICRO_VERSION 2

/* minor */
#define FOB_MINOR_VERSION 0

/* define if bool is a built-in type */
#define HAVE_BOOL 

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* define if the compiler supports the mutable keyword */
#define HAVE_MUTABLE 

/* define if the compiler implements namespaces */
#define HAVE_NAMESPACES 

/* Define if you have POSIX threads libraries and header files. */
/* #undef HAVE_PTHREAD */

/* define if the compiler supports ISO C++ standard library */
#define HAVE_STD 

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* define if the compiler supports Standard Template Library */
#define HAVE_STL 

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of package */
#define PACKAGE "fob"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "fob"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "fob 1.0.2"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "fob"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.0.2"

/* Define to the necessary symbol if this constant uses a non-standard name on
   your system. */
/* #undef PTHREAD_CREATE_JOINABLE */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "1.0.2"
