######################################################################
# Automatically generated by qmake (2.01a) mer. déc. 1 09:57:37 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += AGHFile.h AGHMainWindow.h
SOURCES += AGHFile.cpp AGHMainWindow.cpp main.cpp
