######################################################################
# Automatically generated by qmake (2.01a) jeu. déc. 2 14:49:53 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += AGHFile.h AGHMainWindow.h
SOURCES += AGHFile.cpp AGHMainWindow.cpp main.cpp
